changelog:
  exclude:
    labels:
      - skip-changelog
    authors:
      - dependabot
      - dependabot[bot]

  categories:
    - title: Breaking Changes
      labels:
        - breaking change
    - title: New Features
      labels:
        - type: feature
        - type: enhancement
    - title: Bug Fixes
      labels:
        - type: bug
    - title: Documentation
      labels:
        - type: documentation
    - title: Refactoring
      labels:
        - type: refactor
    - title: Performance
      labels:
        - type: performance
    - title: Security
      labels:
        - type: security
    - title: Infrastructure
      labels:
        - area: infrastructure
    - title: Dependencies
      labels:
        - dependencies
    - title: Other Changes
      labels:
        - '*'
